M48
; DRILL file {KiCad 7.0.7} date Tue Nov  7 19:48:18 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-07T19:48:18-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1160
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1358
%
G90
G05
T1
X2.79Y-1.43
X2.79Y-4.43
X7.79Y-1.43
X7.79Y-4.43
T2
X2.83Y-1.7
X2.83Y-2.6
X3.2Y-4.4
X4.1Y-4.4
X4.29Y-4.4
X5.19Y-4.4
X5.38Y-4.4
X6.28Y-4.4
X7.755Y-1.69
X7.755Y-2.59
T0
M30
